#include 'Global.var'


	PROGRAM _MAIN          
	Feedrate(3500);    //move with reduced speed      
	 MoveJ(HOME); 
//	 MoveJ(P0);        //move system to point P2 
//	 MoveL(P1up);        //move system to point Home     
//	 MoveL(P1);
//	 WaitTime(3);        //wait for 3 seconds 
//	 MoveL(P1up);
//	 MoveL(P2up);
//	 MoveL(P2);
//	 WaitTime(3);
//	 MoveL(P2up);
//	 MoveL(P0);
//	 MoveJ(HOME);


	END_PROGRAM